repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black --preview
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: napari-plugin-test
        name: napari-plugin-test
        stages: [commit, push]
        language: system
        entry: pipenv run napari -v --plugin-info -w napari-kics
        types: [python]
        pass_filenames: false

      # - id: mypy
      #   name: mypy
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run mypy
      #   types: [python]
      #   pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit, push]
        language: system
        entry: pipenv run pytest
        types: [python]
        pass_filenames: false

      # - id: pytest-cov
      #   name: pytest-cov
      #   stages: [push]
      #   language: system
      #   entry: pipenv run pytest --cov #--cov-fail-under=100
      #   types: [python]
      #   pass_filenames: false
